### ISSUE TITLE
Mention `Cmd.Extra.message` in FAQ?

### ISSUE THREAD

**Issue by jvoigtlaender** [shmookey/cmd-extra#1]
It might make sense to mention this function at http://elm-community.github.io/elm-faq/17.html#how-do-i-generate-a-new-message-as-a-command. Repository for a corresponding pull request is here: https://github.com/elm-community/elm-faq.

**Comment by shmookey** [comment]
Agreed. Done: https://github.com/elm-community/elm-faq/pull/24
